### ISSUE TITLE
No Skype notification

### ISSUE THREAD

**Issue by fcaronte** [edotassi/AmazMod#100]
Like title skype notification are not working

**Comment by lfom** [comment]
@fcaronte @GrinFactor only Skype, Skype lite or both Skype and Skype lite?

**Comment by GrinFactor** [comment]
I need it for Skype as my company uses it to correspond with clients and staff. I've never used Skype lite... But I'm assuming it will be needed as it will still communicate with normal Skype users and functions

**Comment by lfom** [comment]
I didn't mean "needed", I meant "tested"...

**Comment by fcaronte** [comment]
Can confirm on Skype lite notification are working

Super PS for now I cannot test with last server because haven't a of where I am for now so I don't know if you update are on server side

**Comment by lfom** [comment]
Added notifications, but replies do not work for some reason I cannot explain.

**Comment by edotassi** [comment]
we can close?

**Comment by lfom** [comment]
@edotassi I don't think so, maybe after replies work with Skype too?

**Comment by lfom** [comment]
1.051/1588 and notifications work (pic by @fcaronte). Replies still don't work tho.
![2018-09-26 14 31 11](https://user-images.githubusercontent.com/15659999/46097729-ff775300-c198-11e8-8c02-be143865cb49.jpg)

**Comment by GrinFactor** [comment]
It does not work if you do not have the service apk... I need it to work without the service apk as I do not use it.

**Comment by GrinFactor** [comment]
I randomly received one skype message yesterday on the watch from the 100s I received during the day (my company uses skype to communicate internally and with clients). But I only received one Skype message...

**Comment by edotassi** [comment]
is there any news?

**Comment by GrinFactor** [comment]
Still does not work on Amazmod, works perfectly on Watchdroid though. I'll install Amazmod later today and try again.

**Comment by edotassi** [comment]
very strange behavior. can you recognize a pattern in notifications that don't reach watch?

**Comment by lfom** [comment]
Skype calls don't use notifications nor change the "ring status" on phone, that's why AmazMod or any other app that relies on notifications can detect it.
