### ISSUE TITLE
Messages not displayed fully in notification center

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#103]
Incoming messages popup displays the entire message but the notification center does not... The notification center(swipe up) only displays a partial message like the original Amazfit app did with Gmail. Watchdroid displays the complete message.

**Comment by GrinFactor** [comment]
Yes I'm sure i enabled "ungroup notification settings"
Screenshot of my settings:
![screenshot_20180813-122253_amazmod](https://user-images.githubusercontent.com/42338862/44026646-00c9e0f0-9ef4-11e8-87ee-4794b9b178ef.jpg)



**Screenshot of receiving your email notification**
![20180813_122128](https://user-images.githubusercontent.com/42338862/44026706-3f276200-9ef4-11e8-9357-77f47f7315a0.jpg)

**Comment by lfom** [comment]
First Gmail notification won't be ungroup, so the extra text won't be displayed in the "standardUI" notification. We must decide it is worthy to create a new rule just to ungroup first notifications with the also side effect of not being able to remove them from phone when they are removed from watch (as every "ungrouped" notification) or not...Personally, I do not think it is.

**Comment by GrinFactor** [comment]
Thank you for the update. 

Take a look at watchdroid... it displays the message/email correctly.

**Comment by lfom** [comment]
We are not WatchDroid, and we use a completely different system, so what works for them might not work for AmazMod.

**Comment by GrinFactor** [comment]
Apologies, I meant no disrespect... I just felt that you since it is possible via WD it could be implemented on Amazmod. I know that WD has been around for a lot longer than Amazmod... 
The implementation of Amazemod I feel is a lot cleaner than WD and has much more potential.

My experience is only with WD(hence my references). I just feel that you guys have something great here and would love it to have all the great abilities.

**Comment by lfom** [comment]
Closed as dup of #114.
