### ISSUE TITLE
Amazmod notification pop gap between title and body too big

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#105]
New incoming messages displayed during the popup display has a big gap between the title and the body of the message.

**Comment by GrinFactor** [comment]
Example of the gap between title and body. 

![20180813_194018](https://user-images.githubusercontent.com/42338862/44048473-afb56020-9f31-11e8-8ec1-2842aaa6ac3d.jpg)

**Comment by lfom** [comment]
Closed after commits 74ea22c151ead4cb532c8b24bb58952b266f37ba and 74ea22c151ead4cb532c8b24bb58952b266f37ba.
