### ISSUE TITLE
Receiving multiple messages (WhatsApp msgs with img)

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#106]
When receiving multiple messages from a single person or multiple messages in a group it only displays the last message or the number of messages... I want to be able to view each message. Not being able to read each individual message makes it impossible to follow the conversation.

**Comment by lfom** [comment]
With what app this happens? Messages are either ungrouped (each notification shows the complete text for that message) or the full conversation is displayed in the most recent notification if it is available in the original notification.

**Comment by GrinFactor** [comment]
This was resolved by using the ungroup option. I was also recently told that it is not possible to ungroup gmail messages like on WD. 

So this issue can be closed

**Comment by lfom** [comment]
Gmail will be ungrouped, if the setting is enabled and the notification is actually a "grouped notification". Some apps send only grouped notifications, some send only after the first one, so there is no fixed rule for this.

**Comment by lfom** [comment]
Gmail content is discussed here: https://github.com/edotassi/AmazMod/issues/103#issuecomment-412525177

I didn't test WhatsApp with embedded images, so reopening this one as bug.

**Comment by lfom** [comment]
I have received a couple of messages with images and no problems here, so closing this issue.
