### ISSUE TITLE
Amazmod widget and app drawer icons... what is the purpose

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#108]
What is the purpose of the Amazmod widget? Also the "Notification" in the app drawer, when you open it all it does is display 
" Amazmod" 
"00:00" 
"Welcome to Amazmod" 
"Close" "Keep"
When you press "close" it closes the screen, and when you press "keep" it closes the screen.

Explaining with an example would be great.

**Comment by GrinFactor** [comment]
I feel the widget has no purpose and should be removed. all the info can be moved to the amazmod "notifications app" in the app drawer.

**Comment by lfom** [comment]
As @fcaronte already said on XDA, widget can be disabled using SB Settings as any other widget, and it will be used in the future, so disabling it while AmazMod is beta makes no sense. Closing this one.
