### ISSUE TITLE
Reply to sms

### ISSUE THREAD

**Issue by airainchoc** [edotassi/AmazMod#111]
Is it possible to add a way to reply to SMS ?

That's the only reason I see for using canned answers, and it does not work

**Comment by lfom** [comment]
Can you please report the phone model and Android version? Also the name of the app package used for SMS that is displayed in the Notifications log in AmazMod? It might not be possible, but if you use another app for SMS (YATA, Contacts+, etc) then you might be able to reply as other people reported that they can reply to SMS.

**Comment by airainchoc** [comment]
I tried with another SMS app, and it seems to work. So it's definitly a bug with Miui SMS app

**Comment by edotassi** [comment]
Ok, since it seems to be a problem with the miui, can it be closed?

**Comment by lfom** [comment]
I am not sure, I had to add Contacts+ to whitelist manually to get notifications, and I haven't tested replies. I am not sure if replies work with most SMS apps or if it even works (@fcaronte didn't reply confirming).

**Comment by airainchoc** [comment]
Well, from my tests, answers are working with "Mood" (plus I like it's interface)
But no way to make it work with Miui original app.

If someone can confirm if it works with android SMS app (because I think Miui one is the same)

**Comment by fcaronte** [comment]
I confirm I can reply SMS but I'm on Samsung SMS and in log the name is "com.samsung.amdroid.messaging" ps only test by sending SMS myself and test only with Samsung stock app
