### ISSUE TITLE
App don't synchronise with watch

### ISSUE THREAD

**Issue by Crissb75** [edotassi/AmazMod#116]
I  followed all  the steps described in the FAQ but nothing. App Amazmod don't work. I have LG V20 with Android 7.0. Please help me to syncro app with watch.

**Comment by lfom** [comment]
Sorry, GitHub isn't a place for support. The options are:

Support:
International:
- https://www.facebook.com/groups/HuamiAmazfit.Pace.Smartwarch/
Italian:
 - https://www.facebook.com/groups/Italiamazfit/
 - https://t.me/joinchat/GK1rkg-rXcATxgfTenq9sg
Brazilian:
- https://t.me/Amazfit
- https://t.me/ptBRpacebip

Thanks.
