### ISSUE TITLE
Music control via physical buttons of the watch on the smartphone

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#117]
If possible, set upper double press to skip forward, double press skips back, if its possible at all

**Comment by lfom** [comment]
if it's even possible while service app is in the background (I don't think it is) it probably will demand a lot of battery...

**Comment by 1immortal** [comment]
it was just a questioned request, i'm solly mistel :(

**Comment by lfom** [comment]
Can be closed after commit https://github.com/edotassi/AmazMod/commit/fab9995ca4c779796a039e8cc275742617b98852?

**Comment by edotassi** [comment]
yes we can close, but in the next update i will remove it
