### ISSUE TITLE
No notifications of SMS/MMS on MIUI

### ISSUE THREAD

**Issue by DriffeX** [edotassi/AmazMod#12]
If I enable "Original notifications" option in Mod's settings, I cant receive notifications of stock SMS/MMS app. Notifications of third party apps works good. 
If I disable "Original notifications" option in Mod's settings, I receive notifications of stock SMS/MMS app, but I receive duplicates notifications from third party apps. 
Xiaomi Mi6, MIUI 9 (Android 8.0)

**Comment by edotassi** [comment]
with 4.1.6 is it fixed?

**Comment by edotassi** [comment]
@DriffeX can you record a logcat?

@cavazzatommaso did you check the permissions? have you tried restarting your watch and phone?

**Comment by cavazzatommaso** [comment]
Working with the 3.0.0 version

**Comment by cavazzatommaso** [comment]
@edotassi yep i've tried

**Comment by edotassi** [comment]
@cavazzatommaso can you record a logcat while receiving a notification?

**Comment by cavazzatommaso** [comment]
@edotassi how i can?

**Comment by DriffeX** [comment]
I record logs and send it with user Varius))

**Comment by DriffeX** [comment]
Sorry, I inadvertently closed issure.

**Comment by fcaronte** [comment]
Probably no SMS too on my s7, need some other test

**Comment by lfom** [comment]
Yes, same here. O think app needs some other permissions to access SMS notifications. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fcaronte** [comment]
For me with today install (push notification if screen on in lockscreen) SMS are working

**Comment by edotassi** [comment]
can be closed?

**Comment by lfom** [comment]
Yes, I think so. With the code currently being used, it should work unless the app hides the notification content somehow, like in Google Maps. SMS access isn't required.
