### ISSUE TITLE
Microsoft outlook app - RTL notifications are reversed

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#120]
https://play.google.com/store/apps/details?id=com.microsoft.office.outlook

when an email from that app arrives and there's a notification with header and some body text, everything in Hebrew is reversed , like in the stock lockscreen.
Outlooks' fault or Amazmod's?

**Comment by lfom** [comment]
Both in customUI and standardUI? Screenshots? Proofs?

**Comment by 1immortal** [comment]
I'm standard its flipping due to the lock screen slpt mode, where all RTL
is flipped, in custom UI, it's flipped as in the stock one, I'll attach
images.

**Comment by 1immortal** [comment]
Outlook notifications are displayed by the stock notification system from some reason. Its selected in the amazmod, but still, when an email arrives, the stock one kicks in.

**Comment by 1immortal** [comment]
![screenshot_2018-08-14-09-29-44-0889332601](https://user-images.githubusercontent.com/5845985/44075410-654901e4-9fa5-11e8-8a8e-abbcd0a92e65.png)
![screenshot_2018-08-14-09-31-43-1452236951](https://user-images.githubusercontent.com/5845985/44075412-658a10a8-9fa5-11e8-90b5-b006bacbc4a7.png)

**Comment by lfom** [comment]
LOCALOK notifications do not trigger the replies (customUI) as they usually don't have any interactions anyway, so maybe we will have to add it to the fixed whitelist too...

**Comment by 1immortal** [comment]
If possible to add to whitelist, that could be great

**Comment by lfom** [comment]
@1immortal Possible fix added in 25e39b3435d76390e4adaa76ab231c25fcb034f8, please check and report back.

**Comment by 1immortal** [comment]
![screenshot_2018-08-19-02-55-07-1150418856](https://user-images.githubusercontent.com/5845985/44304124-b6431080-a35b-11e8-865a-f28ab35cf508.png)

**Comment by lfom** [comment]
Closed after ef1000b443f6eb9de17371ced3532064020b11a0 and f11b81ec7e05e513b386770be05864775327058d.
