### ISSUE TITLE
Notifications delayed when phone screen is off

### ISSUE THREAD

**Issue by skvrnda** [edotassi/AmazMod#121]
There is no problem with stock Amazfit notifications.
But when I deactivate notifications from stock app and activate them just in AmazMod (for the same apps), I receive them only when phone is wake up.
When screen is off - no notifications. I receive them all after unlocking the phone.

AmazMod has same permissions as stock Amazfit. Batery optimization is off for both of them.
Huawei P9 Android Nougat, AmazMod v1.0.25 with AmazMod Service v0.0.1_(1206)

**Comment by airainchoc** [comment]
Seems like you need to force amazmod to stay active (I seem to remember that Huawei battery economy service is super agressive)

**Comment by skvrnda** [comment]
"Keep running after screen off" - it's enabled for both apps.
But with stock Amazfit it works without problems, all notifications are immidiately resend to watch even with screen off, but with AmazMod only when screen is on.

**Comment by lfom** [comment]
But AmazMod doesn't show a notification all the time (I do think it is annoying), then some versions of Android won't respect the "keep running" status...

Maybe we need to add a hidden notification as requested by some systems?

**Comment by skvrnda** [comment]
I've found workaround and it works!
![obrazek](https://user-images.githubusercontent.com/42358093/44092793-cfec36ca-9fd1-11e8-937d-fd8bedb618a3.png)

But it's just an workaround, because it's needed to "Lock an app" every time the phone is restarted.

**Comment by 1immortal** [comment]
on every device, its a little different way of doing that. usually, you
need in recent used apps to pull the app up or down or tap a lock icon for
it to be locked in memory and not killed by the system.
additional thing to be done is to exclude amazmod and amazfit apps from any
battery saving applications, system ones or external ones, for the
smartphone not to kill and hibernate the needed apps in any time.

**Comment by skvrnda** [comment]
But stock Amazfit app stays locked in the memmory with same settings and permissions as AmazMod, which don't.

I am still not sure, if the described workaround works 100%. Because even with that the notifications sometime arrives on the watch through AmazMod immedietely, sometimes the notification arrives even after 5 minutes after it arrives on the phone.

So maybe the whole problem is not in AmazMod doesn't run in backround when screen is off, but **AmazMod sends notifications sometimes with big delay when screen is off (on Huawei phones)**.

With stock Amamazfit, I receive the notification almost immediately it's received by the phone.
Stock Amazfit has one more permission granted: WRITE_SETTINGS (I don't know if it can be related with that problem) and yes, stock Amazfit stays active in the notification bar all the time.

Btw. @SkeddyBot on Telegram is very good for notificatin's testing 😉

**Comment by edotassi** [comment]
@skvrnda if you "Lock an app" AmazMod's notifications are without delay?

**Comment by skvrnda** [comment]
@edotassi no, "Lock an app" has no effect on the delay

After activating "Lock an app" it seemed that everything works like a charm even without delay (tested with @SkeddyBot maybe just a few seconds after screen was off).
But after some time I noticed that the delay randomly appeared. Sometimes the notification arrives immediately, sometimes after 1-5 minutes. If there are more notificatins during 5 minutes, they arrives on watch with delay all together in the same time (one over another).
Then I realized, that with "Lock an app" off the behavior is actually the same.

**Comment by lfom** [comment]
Probably it's the same bug related to when AmazMod is in the background, and the system freezes/stops it.

**Comment by lfom** [comment]
Latest version includes a persistent notification that should fix crash on Oreo and may fix this problem as well. Please confirm this after installing the new version so we can close this issue. Thanks.

**Comment by lfom** [comment]
![device-2018-08-22-171817](https://user-images.githubusercontent.com/15659999/44489747-b597cc00-a632-11e8-9dd4-2a1c2db189ee.png)

**Comment by skvrnda** [comment]
Thanks for the persistent notification. But the behaviour is still the same: notification sometimes arrives to the watch immediately, sometimes after a minute, sometimes after 5 minutes.

Tested on v1.0.32

**Comment by lfom** [comment]
No more reports about this issue, closing it as of 1.0.49 release. Please re-open with more info if it persists...

**Comment by grmendes** [comment]
I'm facing this bug in new version (currently 1.1.3, beta program). Before beta updates, it was working normally, but now I'm facing some delayed notifications. I'm using a Samsung Galaxy A8 with Android 8.0.

**Comment by lfom** [comment]
@grmendes Make sure you use only one kind of notification (standard or custom/replies) and that AmazMod isn't killed in the background by any battery saving program (if you have issues with this, then enable the persistent notification). If you still have problems, please find an open issue or create a new one, and add all the info you can about the problem.
