### ISSUE TITLE
Background exception in Android Oreo devices

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#123]
Background exception in Android Oreo devices:

Caused by java.lang.IllegalStateException
Not allowed to start service Intent { cmp=com.edotassi.amazmod/.transport.TransportService }: app is in background uid UidRecord{69f3a5e u0a186 RCVR idle change:uncached procs:1 seq(0,0,0)}
android.app.ContextImpl.startServiceCommon (ContextImpl.java:1521)
android.app.ContextImpl.startService (ContextImpl.java:1477)
android.content.ContextWrapper.startService (ContextWrapper.java:650)
com.edotassi.amazmod.AmazModApplication.onCreate (AmazModApplication.java:40)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1120)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:5776)
android.app.ActivityThread.-wrap1 (Unknown Source)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1668)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:172)
android.app.ActivityThread.main (ActivityThread.java:6590)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

**Comment by lfom** [comment]
Should be fixed after 7a120de95795da5bd5b781ce1c191217a25678a0 and 03fcaf8e9504404e038c922655c7471551cd6426, whoever can test this on a real device, please confirm and close (I have checked using emulator with Oreo 8.1 only).

**Comment by lfom** [comment]
No more crashes on Emulator running 8.1, so closing this one.
