### ISSUE TITLE
Google maps double notifications

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#124]
When using google maps to navigate I receive every notification twice, about 0.5-1 second apart from each other. 
You can test quickly by just selecting a destination and clicking start. It will immediately vibrate and display the notification followed by the second one.

**Comment by lfom** [comment]
It's not bug, it's by design: if the content (title or text) is different or it's more than 5min then the notification is pushed to watch. If you start navigation and Maps sends two notifications with different content, this will happen, and it is expected.

**Comment by GrinFactor** [comment]
I will try make a video and send it so that you can see what I mean. I get a notification and then 'n half a second later(probably less than) I get the same notification again. This is easily replicated it I open Google maps and start navigation, immediately I will receive 2 notifications as explained above. I've done the exact same test with Watchdroid and it works normally. Maybe my experience is different to what you are seeing on your phone.

**Comment by lfom** [comment]
I know what you mean, you got two notifications because they are different.
