### ISSUE TITLE
No contact name on incoming call (number only)

### ISSUE THREAD

**Issue by mongo56** [edotassi/AmazMod#127]
This probably isn't an AmazMod issue but still, any help would be welcome.

I've thought AmazMod could solve this for me but it's most likely a firmware issue.
Tried just about everything I can think of and google and I just can't get the contact name to show up on the call notification.

I can see the name just fine. In missed call notification for instance. 
It's just the call interface that's broken.

Any ideas guys?

Stratos (2.3.4.0) - Nokia 7 Plus (Android 8.1)

**Comment by diotto** [comment]
Is your contact phone number configured exactly as it appears in your watch? If yes it's a known issue in amazfit, you only need to format the contact number (there are apps for Android that does this)

**Comment by mongo56** [comment]
All my contact numbers are stored as +xxx xx xxx xxx as they should be.
The number on the watch appears as xxx xxx xxx.
I've tried reformatting a few numbers and it does nothing. 
Not to mention I'm not willing to sacrifice dialing from abroad just to fix this.

**Comment by lfom** [comment]
As it's been said already, it's not related to AmazMod, so I am closing this issue. You can check FAQ if you need general support (those options aren't AmazMod specific).
