### ISSUE TITLE
Receiving Multiple Notifications for calendar eventz

### ISSUE THREAD

**Issue by daenny** [edotassi/AmazMod#129]
When receiving a notification for a calender event I get a new notification (incl vibration) on the watch every minute since in the notification is updated every minute. I.e. It shows the remaining minutes until the meeting. This is very distracting.on the phone only the first notification triggers vibrations.

**Comment by lfom** [comment]
What Calendar app do you use? I use Google Calendar and this definitely does not happen.

**Comment by daenny** [comment]
Outlook for Android

**Comment by lfom** [comment]
@daenny could you please share a screenshot of the Notifications log showing the events? Thanks

**Comment by daenny** [comment]
![screenshot_amazmod_20180819-075104](https://user-images.githubusercontent.com/3392004/44305938-d0451900-a384-11e8-89fe-2985486ee797.png)
![screenshot_amazmod_20180819-075104]
![img_20180817_100320](https://user-images.githubusercontent.com/3392004/44305957-04203e80-a385-11e8-80f9-f0eb15e1d813.jpg)
![screenshot_amazmod_20180819-075549](https://user-images.githubusercontent.com/3392004/44305973-54979c00-a385-11e8-93f6-4161cb0ff316.png)
![img_20180817_100409](https://user-images.githubusercontent.com/3392004/44305979-7002a700-a385-11e8-87c0-8ce76d5e4c5c.jpg)
In the Screenshots you see the office notifications at 10:03:00 and 10:04:00 which also shown on the picture of the watch.

**Comment by daenny** [comment]
I understand that these are several separate notifications, but it's still annoying ;). What would be the easiest way to filter those? Similarly I have a rain alert app which shows the same behavior.. It shows the remaining minutes rain or the minutes until the rain starts in the notification and this is updated on the phone every minute. On the watch i get a new notification every time.

**Comment by lfom** [comment]
@daenny Well, if the content of the notification changes, it's really complicated... As I said, there is already a blocking rule for the same content in less than one hour...

**Comment by lfom** [comment]
Closing it as explanation above, no one else reported a similar issue.
