### ISSUE TITLE
Fix translation and menu voice

### ISSUE THREAD

**Issue by fcaronte** [edotassi/AmazMod#130]
I think the translation need improvement.
1)
In setting the "disable remove notification" is for remove notification on smartphone from swiping it on watch and not the opposite like write on menu.
2)
"Enable voice call notification" i think is for all social call and not only messenger (WhatsApp Skype ECC)
3)
This is only for Italian translation
The "abilità le notifiche di gruppo" could be "abilità separazione notifiche"

**Comment by lfom** [comment]
1. No, it's exactly what is says: it prevents removing notifications from watch when they are removed from phone. The other way around is managed by Amazfit if and only if it still has access to notifications and the notification isn't ungrouped.

2. I think it's pretty clear in the setting summary that it's not only for a certain app, "messenger" is not only that app from FB, but any app that sends messages and can also make call, in this case. By the way, have you tested it with some other app?

3. I will update the translations.

**Comment by fcaronte** [comment]
1- ok understand, so if I reveive a notification both phone and watch and open phone to open notification, the notification got clear on watch or is not happened because of ungroup?

2- ah ok I see messenger like the Facebook app, and no, cannot test for now any call notification :(

3- ok Thanks

**Comment by fcaronte** [comment]
2- tested voice call and seem to work only with Facebook messenger. Test done:
Skype: nothing arrive
Skype lite: arrive notification of lost call
WhatsApp: arrive notification of lost call
Fb Messenger: work well

Super PS for now I cannot test with last server because haven't a of where I am for now so I don't know if you update are on server side

**Comment by scarapunzi** [comment]
3 Italian Translations fixed!

**Comment by lfom** [comment]
@fcaronte i will take a look on Skype calls when I have time... WhatsApp changed something in the app recently, sometimes it doesn't identify itself as a call, that's why it does not work all the time.

**Comment by lfom** [comment]
Skype lite does not use notification when a call is received so it won't work with the current code, if the normal Skype doesn't show a notification when a call arrives, like WhatsApp do, then it's the same...

**Comment by lfom** [comment]
Closing this one, i don't think Skype calls can be "fixed" anytime soon as it does not show notifications...
