### ISSUE TITLE
Lack of swipe out notification feature

### ISSUE THREAD

**Issue by EgorOA** [edotassi/AmazMod#132]
Hi!

New notifications with AmazModService is greate thing, especially interactive mode (replies).
But there is a greate lack of a swipe out function (left to right swipe) - it may be very usefull when u do not want to reply but only close received message.
Thanx in advance!

**Comment by lfom** [comment]
Scroll down, there is a Close button for this. Swipe may be used in the future for other things.

**Comment by EgorOA** [comment]
U r not right. Close button is very deep, u have to do a lot of movement to close message and there is a problem with undesired tap to answer while closing. And look at likes on feature request– it will be very usefull and convenient way to close message!
