### ISSUE TITLE
AmazMod.v.1.0.26 Hungarian

### ISSUE THREAD

**Issue by gidano** [edotassi/AmazMod#134]
Hi Edo,</b>
a note. I would like the English terms would be moved from source code into language files. It would be much more beautiful if there were no English terms in Hungarian UI. The same applies to the service file, some of which are Hungarian and the other part are English. I'm thinking of what I'm currently seeing in the smali files. There is not much. :)</b></b>

Thx,</b>
gidano</b></b>

[AmazMod.v.1.0.26-HU.by.gidano.zip](https://github.com/edotassi/AmazMod/files/2290998/AmazMod.v.1.0.26-HU.by.gidano.zip)

**Comment by lfom** [comment]
HU translation was old, and new strings were added that wan't translated. The XML files need to be updated. Does the attached file contain updated XML files with HU localization? If yes, I can extract them and replace the ones used currently.

**Comment by lfom** [comment]
@gidano I meant: when I started working on AmazMod there were already HU localization files, but new strings were added and they were not translated, that's why you see some text in English. The file you attached has the XML file with everything translated?

**Comment by gidano** [comment]
Yess!

Üdv.
gidano
Samsung S8

lfom <notifications@github.com> ezt írta (időpont: 2018. aug. 16., Csü
21:28):

**Comment by gidano** [comment]
@lfom: It is partially English in addition to the Hungarian UI because the source still contains English terms that are not included in the language files! :)

**Comment by lfom** [comment]
@gidano Yes, I added a few more to the strings... But we cannot change private resources, Android Studio will complain. ;)

**Comment by gidano** [comment]
@lfom: Ok I understand! :) So it will be.

**Comment by lfom** [comment]
Closed, new localization available on #161.
