### ISSUE TITLE
[feature request] review notifications (with reply option) 

### ISSUE THREAD

**Issue by daenny** [edotassi/AmazMod#135]
When using the custom ui, the notifications are closed after a certain amount of time. The only acces is then via the "normal" amazfit notification system. In the app that I used before (AMF https://www.guatedroid.com/amf/watch-app-installation/) you could review the notifications via the springboard UI and use the custom reply. This enables you reply to a notification at a later stage even if you missed the custom ui screen.

**Comment by daenny** [comment]
I just checked this might be a duplicate of https://github.com/edotassi/AmazMod/issues/114 (if I understand his request correctly)

**Comment by lfom** [comment]
Yes, closed as dup. Thanks.
