### ISSUE TITLE
Ability to cancel notification reply

### ISSUE THREAD

**Issue by diotto** [edotassi/AmazMod#136]
It would be great if Amazmod could allow you to cancel a notification reply.
If I click in a predefined response it could show a countdown like "Replying notification in 3....2...1..." with a cancel button 
It helps when you click accidentally in reply button.

**Comment by lfom** [comment]
Do not expect this any time soon, maybe in the long term...

**Comment by EgorOA** [comment]
I have a similar suggestion https://github.com/edotassi/AmazMod/issues/137#issuecomment-413880479

**Comment by diotto** [comment]
@lfom , a "Reply" button, as suggested by @EgorOA would be a great improvement. Makes the UI cleaner (i have around 10 canned responses so close button is two or three screens down) and also solves the problem of replying by mistake.

**Comment by lfom** [comment]
![ss01](https://user-images.githubusercontent.com/15659999/44489603-415d2880-a632-11e8-94f9-234610cc59ea.png)

**Comment by diotto** [comment]
Great! Thanks.

**Comment by diotto** [comment]
Solved by @lfom with the "Reply" button.
