### ISSUE TITLE
Option to disable notifications on the custom UI, enable only the UI

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#137]
Option to disable notifications on the custom UI, enable only the UI

**Comment by lfom** [comment]
You mean disable replies in the replies (custom ui)? Really? What is so bad about the buttons with the replies? You can also delete all replies if you don't want to use then, you know...

**Comment by EgorOA** [comment]
I think that a good way to reply is a touch on message text and only then reply buttons arised.
Not every notification needs to be replied, but persistence of reply buttons on every message makes a possibility of mistake answer. 
There will be a greate feature when u can choose an option what to do with the message - to close message or to reply on it. U can do it by swipe left or swipe right e.g.

**Comment by lfom** [comment]
Closed after ef1000b443f6eb9de17371ced3532064020b11a0.
