### ISSUE TITLE
Even if watch is connected, battery graph is always "waiting for data"

### ISSUE THREAD

**Issue by scarapunzi** [edotassi/AmazMod#138]
As displayed in screenshot (in attesa dei dati= waiting for data)
![photo_2018-08-17_12-35-03](https://user-images.githubusercontent.com/37537019/44262073-fbf7c000-a219-11e8-8abe-d0d2526e1f46.jpg)

**Comment by fcaronte** [comment]
Need to charge at 100% and stay in charge to wait sync and give 100% on the app too and then is working

**Comment by lfom** [comment]
As fcaronte said, it will display the correct date when you fully charge the battery after installing service APK, there is no way to know the last time it was fully charged, obviously.

**Comment by scarapunzi** [comment]
Perfect, thank you for explanation!
