### ISSUE TITLE
Amazmod service not working

### ISSUE THREAD

**Issue by gianm96** [edotassi/AmazMod#139]
![screenshot_amazmod_20180817-130034](https://user-images.githubusercontent.com/36802208/44263038-a58c8080-a21d-11e8-931d-763d39efd005.png)
![screenshot_amazmod_20180817-130043](https://user-images.githubusercontent.com/36802208/44263053-b2a96f80-a21d-11e8-80cd-a4c99af7057a.png)
![screenshot_amazmod_20180817-130053](https://user-images.githubusercontent.com/36802208/44263057-b89f5080-a21d-11e8-8fa9-c225f359d26c.png)
![screenshot_amazmod_20180817-130057](https://user-images.githubusercontent.com/36802208/44263063-bccb6e00-a21d-11e8-92e0-6c33e6327a0b.png)
![img_20180817_130435](https://user-images.githubusercontent.com/36802208/44263155-20ee3200-a21e-11e8-9bd9-67f1912fd9e0.jpg)
My problem is that the battery chart doesn't load the info since yesterday and the amazmod app doesn't load the watch info. Also i receive the notifications but I can't reply. In the screenshots there is my setup. I have a modded version of the original Amazfit Watch App, the old Amazmod 4.1.6. Either the Amazfit App and the Amazmod App are set without battery optimization. I have the Pace and a Oneplus 3T with Android 8.1.

**Comment by lfom** [comment]
Remove old AmazMod, it may cause problems. You must either use it only, or new AmazMod and stock Amazfit.
