### ISSUE TITLE
AmazModService screen - add period from last charge 

### ISSUE THREAD

**Issue by EgorOA** [edotassi/AmazMod#141]
Add text this the period from last charge on service screen on the watch, please.
There is a lack of this info in new ROMs.
![44263155-20ee3200-a21e-11e8-9bd9-67f1912fd9e0](https://user-images.githubusercontent.com/25991277/44271310-59473d80-a229-11e8-9236-644f2606c08e.jpg)

**Comment by lfom** [comment]
There is no lack of data, it will show the date when you fully charge the battery and then disconnect the charged after installing service APK, it doesn't get the data from Amazfit because it tracks any charge, not only fully charge.
