### ISSUE TITLE
Czech language

### ISSUE THREAD

**Issue by Puzzlehead0** [edotassi/AmazMod#148]
Hi,
I translated AmazMod to Czech language.

[Czech language.zip](https://github.com/edotassi/AmazMod/files/2301529/Czech.language.zip)

**Comment by edotassi** [comment]
thanks, can you do a pull request?

**Comment by Puzzlehead0** [comment]
Sorry, I don't know how can I do a pull request and what is this. :-(

**Comment by lfom** [comment]
I will add the files manually. I hope someone can fork and keep them updated later. Thanks.
