### ISSUE TITLE
Build of Amazmod Service fails with missing google-services.json 

### ISSUE THREAD

**Issue by yaronkle** [edotassi/AmazMod#150]
Trying to build 1229 from downloaded sources and I am getting a build failure of missing google-services.json
Copied manually from the AmazMod-1229\old\patched folder and modified package name

**Comment by edotassi** [comment]
it's a private file, I'm checking if I can publish it freely

**Comment by daenny** [comment]
You can generate your own of you are registered with google/firebase: (see first answer) 
https://stackoverflow.com/questions/34367870/where-do-i-get-a-google-services-json
Be careful to name your app exactly as the package. If I remember correctly it's 'com.edotassi.amazmod'

**Comment by GreatApo** [comment]
The file is not in the sources.
It can be closed.
