### ISSUE TITLE
Updating the Service APK from AmazMod

### ISSUE THREAD

**Issue by morlenxus** [edotassi/AmazMod#153]
Would be nice, if once the service apk has been installed on watch, it never needs to be updated manually. AmazMod could push the apk on update to the watch and the service apk installs the update (or maybe the AmazMod could do that using the adb command). Just an idea. :)

**Comment by edotassi** [comment]
it would be very interesting :)

**Comment by lfom** [comment]
@edotassi Won't this be a problem to publish the app on Play Store?

**Comment by edotassi** [comment]
@lfom it'a a problem if the app update itself, but the service on watch don't use play store
however I am not an expert in the law :)

**Comment by 1immortal** [comment]
you can't install from the playstore stuff on the watch, and sending the
apk to the watch to get installed - you need to change some system settings
on the watch and change the layout of the installer to be able to approve
the actual installation, thus, modded rom or some magisk/xposed - again -
impossible.

**Comment by lfom** [comment]
This should work too:
adb connect IP
adb install -r service.apk

but we can only start to think about this once file transfer is implemented...

**Comment by edotassi** [comment]
follow in #223
