### ISSUE TITLE
unable to update

### ISSUE THREAD

**Issue by rafilkmp3** [edotassi/AmazMod#154]
Hi i tried to update to latest version and i was blocked for the following error

```
┗ adb install -r AmazMod-service-1277.apk
AmazMod-service-1277.apk: 1 file pushed. 1.5 MB/s (2840109 bytes in 1.796s)
	pkg: /data/local/tmp/AmazMod-service-1277.apk
Failure [INSTALL_FAILED_DEXOPT]
```

**Comment by edotassi** [comment]
do you have enough free space on watch?

**Comment by rafilkmp3** [comment]
yes i do.

**Comment by rafilkmp3** [comment]
i fixed removing the previous version with: 
`adb shell pm uninstall  com.amazmod.service`
then I installed with success the latest one : 
`adb install  AmazMod-service-1277.apk`

**Comment by the4anoni** [comment]
I have this same error.
I have free space, and not installed service apk.
Installed using adb install.
