### ISSUE TITLE
Amazmod 1.0.32 - Disable stock notifications enhancement request

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#156]
This feature addresses the issue that many users experienced (double notifications) - and you did explain why we received two notifications. Unfortunately, this removes the ability to view notifications. Example:  you received 5 notifications in a row, but since you can only see the message on the custom UI you will lose the other notification as there is no messages in the drawer. 

Is possible to keep the drawer functionality and hide/make invisible the stock notification? This way we can still view the other messages and not just the one displayed in the custom UI.

**Comment by lfom** [comment]
Dup of #114.

**Comment by GrinFactor** [comment]
This is not a dup of #114 ... I like the way Amazemod pop looks and works with Custom UI. I just want the stock UI notification that appears with the custom UI to be hidden/invisible so that it still enables us to view messages in the stock UI drawer. 

The #114 Does not want that, That request is to display email messages' body and reply from history, I do not want that.

All I want is to see my missed messages in the drawer when I was not able to see them during custom UI popup without "feeling" like i'm receiving two messages.
