### ISSUE TITLE
Huawei honor 6x

### ISSUE THREAD

**Issue by Nofly67** [edotassi/AmazMod#16]
Hi,
i tried several amazit app version (2.0.0 - 2.1.0 - 3.0.0 ) for the amazfit pace with Sagliano 6.0 ita rom, but after the paring, notifications didn't arrive to the watch. I set everything to keep the application opened, but no notifications arrives. Any solutions?

**Comment by edotassi** [comment]
see #40

**Comment by edotassi** [comment]
see #40
