### ISSUE TITLE
Amazfit Pace Rom 2.8.0.5 - AmazMod 1.0.32 Connecting loop

### ISSUE THREAD

**Issue by nanodreams** [edotassi/AmazMod#162]
Hi,

I tried all 3 versions so far of then new AmazMod but seems I'm not lucky. From the documentation it says it will automatically connect ... but I can't make it. I've done all this with same results

**Devices**
Amazfit Pace US Rom 2.8.0.5
AmazMod Version 1.0.32
Samsung S8

**Troubleshootings**
_Watch_: 

- Rebooted
- Flashed with latest 2.8.0.5
- Flashed with 1.X, then upgraded via OTA.

_Apps_:

- Uninstall / Install Amazfit and AmazMod several times.
- Rebooted phone.

After all this steps, the AmazMod Apps still displaying:
"Watch's information"       CONNECTING...

Is there anywhere I can check the logs to see the actual error? Debug mode?

Regards and thanks for the efforts and bringing this to our Amazfits ;-)

**Comment by lfom** [comment]
Did you read the FAQ? You need latest stock Amazfit installed on phone, new AmazMod does not replace it, but requires it to be installed.

**Comment by nanodreams** [comment]
@lfom 
Yes, sorry forgot to add also details about the Amafit App. 
I did indeed read several times the FAQ, but no one had any problems connecting the App, that was what a bit surprise ... it's ony me? Maybe phone related? Only have one android ... so can't test unless reset to factory (not really in the mooth to reinstall the phone, :-( ). I've waited 3 releases to make sure it isn't something "known" that would be patched. 

**Details**
Amazfit Pace US Rom 2.8.0.5
AmazMod Version 1.0.32
Amafit App 2.5.2.1 with Algorithm 1.1.09
Samsung S8

Thanks for your help.

**Comment by lfom** [comment]
Test notifications from Amazfit *and* AmazMod work? To send test notifications in AmazMod, tap the 3 dots menu in the About screen. If Amazfit works, there is no reason for AmazMod to not work, even installing app on watch is optional... Now I see that you didn't say that you installed the service APK on watch, without it AmazMod won't connect, obviously. But basic notification filtering will work.

Sorry, but GitHub isn't meant to support. I suggest that you post your problem in any of the suggested places you can find in the FAQ.
