### ISSUE TITLE
Custom UI notifications - "nagging" mode

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#166]
repro steps:
1. got a message on whatsapp on my phone. **did not read it**
2. i'm getting a notification about the unread message on the watch every time there's an event on the phone:
i got a new telegram notification -> i'll get the unread whatsapp notification again.
maybe add a reminder of unread messages like:
- Do not notify again if not read on watch
- Remind after 5 minutes
- Remind after 15 minutes
- Remind after 30 minutes

and limit the amount - after the last reminding, it will be accessible in the drawer only, regardless if read or not read on the watch.

pros/cons ?

**Comment by lfom** [comment]
I have never had this behavior of repeating notifications, only when some app *updates* an existing notification (i.e, sends another notification but with different content, for example a calendar sends 1h to event, then later 30min to event, etc).

**Comment by edotassi** [comment]
is this issue still valid?

**Comment by 1immortal** [comment]
yes and no, it still happens when there's new notifications in an app, but i still havent read the first one, i'll keep getting the first one over and over again in the watch.
