### ISSUE TITLE
Settings menu enhancement - avoid exiting and entering constantly.

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#174]
When making changes to any setting, Amazmod then takes you to the home screen. This is very frustrating as you need to re-enter the settings screen each time you make a change. Is it not possible to make a change on a menu option and go back to the settings menu without needing to exit completely every time?

**Comment by edotassi** [comment]
can be closed?

**Comment by GrinFactor** [comment]
No, do not close. I'm using 1.0.34. When I make a change in settings and click the <-- button it takes me to the Amazmod default(home) screen. It should take me back to the settings menu.

**Comment by GrinFactor** [comment]
I was not aware and I can not test it. If you say it has been fixed then I'm grateful and very happy

**Comment by edotassi** [comment]
ok i close now
 @GrinFactor check in the next public update and reopen if necessary

**Comment by GrinFactor** [comment]
will do :) thank you
