### ISSUE TITLE
Amazmod 1.0.34 wrong battery reference

### ISSUE THREAD

**Issue by steverimini** [edotassi/AmazMod#175]
I completely charged my stratos and after 19 real hours since the charge, amazmod is showing 1d, 23h!

**Comment by edotassi** [comment]
@steverimini please can you attach a screenshot? thanks

**Comment by steverimini** [comment]
I'm not at the computer now and it seems I cannot attach a file on the phone version of this web site! (or please tell me how to!)

**Comment by steverimini** [comment]
![screenshot_2018-08-31-09-37-55](https://user-images.githubusercontent.com/42836448/44910090-2ff6d900-ad22-11e8-9baa-26d599c22564.png)
![screenshot_2018-08-31-09-37-41](https://user-images.githubusercontent.com/42836448/44910101-38e7aa80-ad22-11e8-8d17-e4627da4929f.png)

**Comment by steverimini** [comment]
Here I am.  As you can see from these two screenshots I got at 9.37, the amazmod says that battery last charge was two days ago,  when amazfit app says 20h (and it is the correct one)...

**Comment by scarapunzi** [comment]
As you can read from the italian translation, amazmod shows time since LAST FULL CHARGE (ultima ricarica COMPLETA). Amazfit shows time since last charge (full or not). Maybe you disconnected before 100% (99 maybe?) or the battery wasn't really fully charged (there is a small thrikle charge time; if you read 100% and you disconnect immediately the charge could not be effectively complete).

**Comment by steverimini** [comment]
I left the battery +-30 minutes more after showing 100%...
I'll try to leave more time and let you know...

**Comment by scarapunzi** [comment]
Did you have this issue again?

**Comment by GreatApo** [comment]
@steverimini so does it work?

**Comment by steverimini** [comment]
Yes, the battery issue is fine, I had to wait more time after 100%is reached. 

And about the second issue I mentioned about the shower time to answer??

**Comment by GreatApo** [comment]
@steverimini In the latest dev version, screen timeout time works correctly. I just changed from Amazmod's settings the screen timeout to 20sec, then clicked refresh and it worked correctly.

I haven't test the previous versions. If this the only problem left, you can close the issue.

**Comment by lfom** [comment]
No problems related to this issue as of 1.0.49 release, so closing it.
