### ISSUE TITLE
Amazmod phone app displays "Connecting" when no service apk is installed

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#191]
Amazmod phone app displays "Connecting" when no service apk is installed. How about just changing it to stating "no service apk installed on watch" instead of saying "connecting". 

This will reduce confusion with new users and point them into the right direction eg. either install the service apk or decide not to install it. 

The "connecting" message also makes users think that the phone is trying to connect to the watch constantly. 
If you're a user like me that does not use the service apk and only uses the message ungroup function(at the moment, waiting for more features get added first), it can make life much easier.

**Comment by rpodgorny** [comment]
+1 ...this confused me a lot!

**Comment by lfom** [comment]
Closed after release 1.0.49.
