### ISSUE TITLE
brightness setting is not being respected by "activate on raise"

### ISSUE THREAD

**Issue by rpodgorny** [edotassi/AmazMod#208]
not really sure if this is even controllable by amazmod but i'm experiencing the following:

* set brightness to very low value using amazmod (lower than level 1 on the watch)
* enable tap-to-activate on the watch
* enable activate-on-raise on the watch
* when i tap the display, the brightness is low (correct)
* when i move the wrist, the brighness is high (probably "level 1" which is set in the watch) - not correct - i'd expect it to be the same as when just tapping

**Comment by rpodgorny** [comment]
side note: if there are two different values that control backlight, it would be nice to be able to set them both (to possibly different values)

**Comment by lfom** [comment]
"Activate on raise" always use a pre-determined brightness, you can check this by setting a manual value for brightness on watch: it's either none if brightness is 0 or some value (my guess is Auto) when it's not zero. It's not related to AmazMod, so closing this issue.

**Comment by rpodgorny** [comment]
well, then this should be considered more like a feature request. ;-)

when i set the brightness on the watch (off/auto/1/2/3/4/5), this value gets saved somewhere and is being used for both "raise" and "tap" cases. when i override this value using amazmod, the original value is still being used for the "raise" case. this is very unintuitive and confusing. it would be nice if amazmod overwrites the value on "all" places in the watch (so it's equivalent to the watch settings ui). or even better - if i was given to set the "raise" and "tap" values separately which would suit my use case perfectly (very low backlight for "raise" - just to peek at what time it is, "high" backlight for "tap" - using the watch ui). currently, i'm unable to achieve this...

just for consideration, thanks...
