### ISSUE TITLE
Telegram call/WhatsApp group notification 

### ISSUE THREAD

**Issue by NicholasSH** [edotassi/AmazMod#219]
Happy with the new update and UI!

I have a few things to point out though.
WhatsApp Group Chat notifications: working in the previous version but does not work too well in this version. I can see alot of it under BLOCK in the change log.
Telegram call notification: does not work. WhatsApp call notification works though.

Just curious about the changelog as well. What does PACKAGE/ONGOING notifications under the changelog mean?

Also, what does the LPM do exactly and how do I disable it? I had to restart my watch to disable it.

Thanks and keep up the good work!

**Comment by lfom** [comment]
1. There was a regression, it was fixed. Thanks for reporting.
2. Only call notification from messengers that use notifications and change the "ring" status of the phone work (it's the case of WhatsApp)
3. The reason why the notification was blocked or allowed
4. When it's enabled, lpm disables BT, touchscreen and locks screen. You can disable it by putting watch on charge and send two more "lpm notifications" (weird, I know, may change in the future)
