### ISSUE TITLE
Can't pair the watch (Stratos)

### ISSUE THREAD

**Issue by zodrac** [edotassi/AmazMod#22]
I installed the app, granted all the necessary privileges, but when I try to pair the watch (with QR) the app said "The is no bluetooth hardware on the phone".  The bluetooth has been activated on the watch and on the phone by the application itself, and all works fine with the Google play Amazfit Watch App.

**Comment by edotassi** [comment]
what smartphone do you have? and which rom on the watch?

**Comment by zodrac** [comment]
I have International stock ROM 2.3.2.7 on the watch and Xiaomi Mi A1 with Android 8.0

**Comment by zodrac** [comment]
Tried with versión 4.0, same result. There is no bluetooth driver or device on this Phone.

**Comment by ymahnovskyy** [comment]
The had the same issue. It asks several times on watch side to confirm pair code. And I don't see that window with accept bluetooth pairing on phone side is in background. Please, try again and check is there modal window in background.

**Comment by edotassi** [comment]
see #40

**Comment by edotassi** [comment]
see #40
