### ISSUE TITLE
Amazmod 1588 / greatFit 3.5

### ISSUE THREAD

**Issue by steverimini** [edotassi/AmazMod#220]
I tried greatfit watch face but battery drain was huge,  10% per hour! What was strange, I had battery drain even without choosing the gratfit watch face...

No problems with Amazmod 1588 version after factory reset and without greatfit installed.

**Comment by fcaronte** [comment]
What's widget you use? Probably is there the problem because I have the same with no more 20%for day

**Comment by lfom** [comment]
Probably not related to AmazMod. These abnormal battery drains seem to be related to firmware bugs in my tests so far. Closing this one...
