### ISSUE TITLE
Service update from the app

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#223]
- [x] detect new update
- [x] download service-release-xxx.apk
- [x] upload to watch
- [x] install
- [ ] reboot watch

**Comment by rpodgorny** [comment]
isn't this a duplicate of https://github.com/edotassi/AmazMod/issues/153 ?

**Comment by lfom** [comment]
Removing and re-adding admin owner isn't needed actually, only if you must uninstall the app, updating it doesn't require these.

**Comment by lfom** [comment]
Last one was replaced with "restart launcher", with no known side-effects so far (0680a8bac07d7b358d27e6aa93688c5f9ce7c5e9). Closing.
