### ISSUE TITLE
Quick "force close" notification after notification

### ISSUE THREAD

**Issue by Rdzeniuch** [edotassi/AmazMod#227]
Notification appears for couple of sec, then i get a quick "force close" notification and watch goes to always on display (locked mode).

Something like this after the notification. It appears and disappears so quick that i can't actually read it.
(This one is only for reference!)
![pobrane](https://user-images.githubusercontent.com/16858207/45958376-9a482400-c017-11e8-9b22-8aa72069900d.png)

Edit: after some observation it seems to appear randomly, and not every time the notification is on the watch.

**Comment by lfom** [comment]
Are you using latest service APK (1588 as of now)?

**Comment by lfom** [comment]
@Rdzeniuch do you have any other app installed on watch that deals with notifications too, besides AmazMod? Do you know how to get a logcat on watch, filtering by "amazmod"? Without further info, it would be hard to find out what's going on, the version I use doesn't has this error on a daily use.

**Comment by Rdzeniuch** [comment]
I will be trying to get the logcat after the "force close". Actually i haven't seen it lately so maybe it is problem with my watch. I will be trying to get logcat If it happens again.

**Comment by edotassi** [comment]
@Rdzeniuch  is there still the problem?

**Comment by Rdzeniuch** [comment]
Haven't noticed it since last post.
