### ISSUE TITLE
New folder and rename in File Explorer

### ISSUE THREAD

**Issue by diotto** [edotassi/AmazMod#232]
Create a button for "New Folder" and an option for renaming items in context menu

**Comment by diotto** [comment]
There is a bug when the path contains spaces.
I tried do put path between ' and also between " (escaped with a \)

**Comment by diotto** [comment]
@edotassi how this command works?

Watch.get().executeShellCommand(command)

I am using it. Do it make some sort of sanitization when the command is sent to watch?

Debugging with logcat (on phone app) it looks like the commands are ok.

**Comment by edotassi** [comment]
@diotto yes you must send a sanitized command
on the watch the command is executed directly as it is sent
