### ISSUE TITLE
Not able to get notification from <Grab> app

### ISSUE THREAD

**Issue by deception83** [edotassi/AmazMod#236]
I used to be able to receive notification from the app in the previous version. But after updating to this latest 1588. The notification doesn't seem to be pushed.

Is there anyway I can clear the notification log in the phone app? I have 1 million worth of past notification due to my light manager app. And tracing to see whether if Grab did send something out is proving difficult.

Maybe you can also add in what is being logged? Since notification like light manager should not be a concern for my watch?

Thanks.

**Comment by lfom** [comment]
Check if you have the app enabled in "selected apps" and also that "local" notifications is enabled. Then please share a screenshot of notifications log showing entries for the App if it still doesn't work for you.

**Comment by deception83** [comment]
Here you go


![screenshot_20180927-235951](https://user-images.githubusercontent.com/21327348/46159396-d1863180-c2b2-11e8-9bad-d3094b5f31c9.png)
![screenshot_20180928-000455](https://user-images.githubusercontent.com/21327348/46159398-d1863180-c2b2-11e8-8a72-3021b833c2c8.png)
![screenshot_20180927-235924](https://user-images.githubusercontent.com/21327348/46159399-d21ec800-c2b2-11e8-82f5-5bff83fd5980.png)

**Comment by lfom** [comment]
Hmm, thanks... The "empty" status for Grab should not happen...

**Comment by lfom** [comment]
@deception83 No, actually I think there is some bug in the notification management code that is causing problems with its notification. Not entry should have an empty status.

**Comment by deception83** [comment]
Ok, just to confirm because it will mean that I have to actually call for a cab for that to happen. 

For the logcat results, does it matter if I kept the option "Disable when screen is ON"?

**Comment by lfom** [comment]
For testing purposes, to make sure the notification is sent, *disable* this option, allow every notification, including local and ungroup.

**Comment by edotassi** [comment]
@deception83 did you manage to get logcat?

**Comment by deception83** [comment]
10-04 17:40:36.343 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.360 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.grabtaxi.passenger|-964021392|null|10181
10-04 17:40:36.360 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.362 I/AmazMod Screen (2471): DnD lowSDK: OFF
10-04 17:40:36.363 I/AmazMod Screen (2471): DnD highSDK: OFF (ALL)
10-04 17:40:36.366 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService getLocalOnly: com.grabtaxi.passenger
10-04 17:40:36.367 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService notificationPackage: com.grabtaxi.passenger / text: Yay, we found you a driver!
10-04 17:40:36.367 D/AmazMod (2471): │ SKC6908X
10-04 17:40:36.367 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService allowed2: com.grabtaxi.passenger
10-04 17:40:36.367 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService _
10-04 17:40:36.367 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.444 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:36.444 D/AmazMod (2471): │ [NotificationService] NotificationService StandardUI: Bundle[{data=com.huami.watch.notification.data.StatusBarNotificationData@4ae24c6<Pkg : com.grabtaxi.passenger, Id : -964021392, Tag : null, Key : 0|com.grabtaxi.passenger|-964021392|null|10181, GroupKey : 0|com.grabtaxi.passenger|-964021392|null|10181, TargetPkg : null>}]
10-04 17:40:36.444 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:37.251 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:37.251 D/AmazMod (2471): │ [NotificationService] [Transport://com.huami.action.notification/add, Time=1538646036433, Data=0], OK
10-04 17:40:37.251 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:43.640 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:43.640 D/AmazMod (2471): │ [NotificationService] notificationRemoved: 0|com.grabtaxi.passenger|-964021392|null|10181
10-04 17:40:43.640 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:44.140 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:44.140 D/AmazMod (2471): │ [NotificationService] [Transport://com.huami.action.notification/del, Time=1538646043644, Data=0], OK
10-04 17:40:44.140 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:51.848 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:40:51.848 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.google.android.gms|1001|128877243|10014
10-04 17:40:51.848 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:02.273 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:02.273 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.mobidia.android.mdm|100|null|10179
10-04 17:41:02.273 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:06.914 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:06.914 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.koo.lightmanager2|2012|null|10269
10-04 17:41:06.914 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:06.923 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:06.923 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.koo.lightmanager2|2012|null|10269
10-04 17:41:06.923 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:08.393 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:08.393 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.facebook.katana|0|c3Rvcnk6MTY4MDg4OTA2OToxNTM4NjM1MDA0MzU1NTcyOjQ1MTc2MTcxMTUyNjY4Nw==|10199
10-04 17:41:08.393 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:08.511 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
10-04 17:41:08.511 D/AmazMod (2471): │ [NotificationService] notificationPosted: 0|com.koo.lightmanager2|2012|null|10269
10-04 17:41:08.511 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by edotassi** [comment]
@deception83 is this issue still valid?

**Comment by lfom** [comment]
@deception83 This means the notification was sent to watch, but as it's "LocalOnly", you will see it only as a "normal" standard UI notification (it remains in system tray):

> 10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService getLocalOnly: com.grabtaxi.passenger
> 10-04 17:40:36.367 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 10-04 17:40:36.367 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService notificationPackage: com.grabtaxi.passenger / text: Yay, we found you a driver!
> 10-04 17:40:36.367 D/AmazMod (2471): │ SKC6908X
> 10-04 17:40:36.367 D/AmazMod (2471): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 10-04 17:40:36.367 D/AmazMod (2471): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 10-04 17:40:36.367 D/AmazMod (2471): │ [NotificationService] NotificationService allowed2: com.grabtaxi.passenger
> 10-04 17:40:36.367 D/AmazMod (2471):

**Comment by deception83** [comment]
@lfom So does that mean that due to how the app's notification is configured, unless I Enable Standard Notifications, I will not be able to receive it?

**Comment by lfom** [comment]
@deception83 yes, both standard notifications and local one from AmazMod.
