### ISSUE TITLE
Enable device owner as instructed

### ISSUE THREAD

**Issue by halilhassan** [edotassi/AmazMod#237]
Even though I have executed the shell command:
adb shell dpm set-device-owner com.amazmod.service/.AdminReceiver
I am still getting the message "Enable device owner as instructed".
I have rebooted both phone and watch and executed the command via the Tweaking option and I still get this message every time I select the "Close" option when a notification is displayed on the watch.

When running the shell command should I expect to see any notification on the watch that the command has been executed succesfully?

Note: The Service was installed using the Windows application.

**Comment by lfom** [comment]
If you installed service APK, rebooted watch and then run the command, then yes, a toast is displayed on watch and device owner is enabled/disabled. Try to do it via adb on computer, it always work for me and you can see the command result on screen too...
