### ISSUE TITLE
Voice call notifications arrives watch when call ended(not answered).

### ISSUE THREAD

**Issue by sayginburak** [edotassi/AmazMod#251]
I just installed the lastest service apk(1588). Voice call notifications(only tried whatsapp and messenger) only arrives watch when caller ends the call. I tried couple of settings but nothing worked. Is anyone having the same issue?

**Comment by lfom** [comment]
This only works when the app adds a notification to phone and it changes the "ringer" value on phone... WhatsApp used to do this, but this changed in a recent update. It works sometimes, mostly when there are no unread messages.
