### ISSUE TITLE
please add option to set brightness level for "auto backlight" (just like for "normal" brightness)

### ISSUE THREAD

**Issue by rpodgorny** [edotassi/AmazMod#257]
when i set the brightness on the watch (off/auto/1/2/3/4/5), this value gets saved somewhere and is being used for both "raise" and "tap" cases.

when i override this value using amazmod, the original value is still being used for the "raise" case. this is very unintuitive and confusing. it would be nice if amazmod overwrites the value on "all" places in the watch (so it's equivalent to the watch settings ui).

or even better - if i was given to set the "raise" and "tap" values separately which would suit my use case perfectly (very low backlight for "raise" - just to peek at what time it is, "high" backlight for "tap" - using the watch ui). currently, i'm unable to achieve this...

just for consideration, thanks...

**Comment by rpodgorny** [comment]
...continuation of https://github.com/edotassi/AmazMod/issues/208

**Comment by edotassi** [comment]
I think we cann't change the brightness value in "raise" mode

**Comment by lfom** [comment]
> I think we cann't change the brightness value in "raise" mode

True, it's hardcoded in the system. Even it's independent from system's brightness setting (A,0..5). Closing.
