### ISSUE TITLE
Load of watch status failed

### ISSUE THREAD

**Issue by phys** [edotassi/AmazMod#258]
Phone: Xiaomi Redmi 4 Prime
OS: MIUI Global 9.6 | Stable 9.6.2.0 (MBEMIFD)
Android Version: 6.0.1 MMB29M

Watch: Amazfit Stratos A1619
Watch Firmware: 2.3.5.0 

AmazMod: 0.0.1 (1588)
AmazMod App: 1.0.50

![img_20181021_094139](https://user-images.githubusercontent.com/1651189/47264038-a3dd8280-d516-11e8-9a24-1bc855c12524.jpg)
![screenshot_2018-10-21-09-41-10-340_com edotassi amazmod](https://user-images.githubusercontent.com/1651189/47264040-a7710980-d516-11e8-9ec3-3747ae4963df.png)

**Comment by edotassi** [comment]
try reboot watch and phone

**Comment by phys** [comment]
I tried. It's something on the phone side, most likely. Because I see the same error if I don't have Bluetooth enabled. And the app doesn't even offer to enable it.

If Bluetooth is on, there may be something else missing. For example, I think a pairing request would be required. I don't see it.

**Comment by lfom** [comment]
@phys closing it as it's not related to AmazMod itself. Make sure stock Amazfit is installed and working fine, then open AmazMod and enable "persistent notification", and make sure MIUI isn't killing either apps or Bluetooth while they are in the background.
