### ISSUE TITLE
AmazMod Hungarian Translation

### ISSUE THREAD

**Issue by gidano** [edotassi/AmazMod#26]
The new Hungarian translation of the app is made, I attach.<br>Please keep the translator name in the Hungarian language file if you do not mind...<br><br>

[AmazMod.v4.1.5.Hungarian.translation.files.zip](https://github.com/edotassi/AmazMod/files/1988044/AmazMod.v4.1.5.Hungarian.translation.files.zip)<br>gidano

**Comment by edotassi** [comment]
Did you have remove the issue?

**Comment by gidano** [comment]
Yes, because v4.1.5 has been released and the language file has to be
updated.

S.
gidano

Edoardo Tassinari <notifications@github.com> ezt írta (időpont: 2018. máj.
8., Ke 21:40):

**Comment by SM-26** [comment]
@gidano
Do you mind to shear where did you get the English version from?

I wish to help translation to other languages

**Comment by gidano** [comment]
Hi,
Here you find: https://github.com/edotassi/AmazMod/tree/master/releases
But why not ask edotassi about the translation?

**Comment by edotassi** [comment]
see #40
