### ISSUE TITLE
AmazMod and Stratos - Disconnected

### ISSUE THREAD

**Issue by Bruder-Tuck** [edotassi/AmazMod#262]
Hello, 
i use the Amazfit Stratos and install above the windows installer die amazfit Service APK on watch. The programm communicated it´s all okay and the installation worked. 

I restart the watch and the phone. After restart i started the applikation Amazfit and then AmazMod. But there is no connection. 

The test notification - about -> test notification AmazFit works. 
But that´s the only one.

At watch i can´t find or see the AmazMod Widget :( 

Please help me to make it work :)

**Comment by Bruder-Tuck** [comment]
Thanks - Now it works <3 :)

**Comment by diotto** [comment]
Great News @Bruder-Tuck ! 
So I'm going to close this issue, ok ? If necessary you can reopen it.
