### ISSUE TITLE
incorrect battery data

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#269]
Got two different values from the Amazfit app and the Amazmod interface, opened and closed both of them few times, both was synced to the watch, Amazfit is the correct one.

![screenshot_2018-10-23-20-19-58 1](https://user-images.githubusercontent.com/5845985/47439441-0d7abc80-d7b5-11e8-9d46-652fd255908d.png)
![screenshot_2018-10-23-20-19-45 1](https://user-images.githubusercontent.com/5845985/47439477-1cfa0580-d7b5-11e8-86c6-d913a8a0d58e.png)

**Comment by lfom** [comment]
Aren't bth 27%? What's wrong?

**Comment by 1immortal** [comment]
not a bug 👍
