### ISSUE TITLE
Wrong Spanish translation

### ISSUE THREAD

**Issue by GreatApo** [edotassi/AmazMod#271]
The translation here is reported as wrong:
![photo5947074463122173116](https://user-images.githubusercontent.com/9620510/47494898-b1fb0e00-d84a-11e8-9cae-4d43144c2e90.jpg)

English:
![photo5947074463122173120](https://user-images.githubusercontent.com/9620510/47494954-dce56200-d84a-11e8-8364-d59737d4cc23.jpg)

**Comment by Saratoga79** [comment]
Done!
