### ISSUE TITLE
Disable auto opening of keyboard in tweaking menu

### ISSUE THREAD

**Issue by fcaronte** [edotassi/AmazMod#280]
Is possible to avoid the opening of the keyboard when you enter in tweaking menu?

**Comment by diotto** [comment]
https://stackoverflow.com/questions/2743559/set-initial-focus-in-an-android-application

**Comment by lfom** [comment]
Closed after https://github.com/edotassi/AmazMod/commit/addb864a7214d1a7659795f4778fb5f8c616d6d8

**Comment by diotto** [comment]
@lfom there is no need to manually close the issues. GitHub automatically closes it when Dev is merged to master. You just need to put a "fixes #issueId"
