### ISSUE TITLE
Silence notifications for a period directly from watch

### ISSUE THREAD

**Issue by diotto** [edotassi/AmazMod#281]
It would be interesting to have an option to silence the notifications in watch custom ui. Maybe having an option to silence only for the current app sending notifications or silencing all apps. Also it would be great to choose time of silence (for example: 5 minutes, 15 minutes, 30 minutes, ...)

Also, in phone app, we could have an option to cancel the silencing.

**Comment by lfom** [comment]
As of now, notifications on watch honor "Silent" mode, so whenever the watch is in Silent mode, there is no notifications. Isn't it enough? Per notification/sender filters is addressed in another issue.

**Comment by diotto** [comment]
Just noticed it's a duplicated from #52
