### ISSUE TITLE
Update Service APK 1702 issue's

### ISSUE THREAD

**Issue by Kookie69** [edotassi/AmazMod#290]
Hi Updated yesterday to the latest App on google play and updating the service APK 1702 was tricky and took a few goes to get it working but now with some messages from the phone i only get the title of the message and no message text and it worked fine with 1588 so i hope this can be sorted thanks love your work and this app.
Oh the phone is a S7 running Android 8.

**Comment by lfom** [comment]
Check settings, they changed and the old "hide replies" now is "hide content". Always check settings after updates, it's still beta.

**Comment by Kookie69** [comment]
Thank you yes i did find it and it's fine now plus the battery use on the watch is so much less with this new update so loving it well done love your work Amazmod.

**Comment by lfom** [comment]
Glad it worked. Thanks.
