### ISSUE TITLE
No Wechat notification

### ISSUE THREAD

**Issue by ikemanet** [edotassi/AmazMod#292]
Hi my friend,

First of all, thank you so much for making this awesome app, I love it and I'm using it everyday.
Today I realized my watch can't receive any message from Wechat, I checked the notification log, every notification from Wechat says 'RETURN', not like others which say 'CONTINUE'.
I also tried 'test notifications', they all worked file.

My settings are the following:
Disable standard notifications: YES
Enable custom replies: YES
Inverted theme: YES
Disable screen on: YES
Disable when screen is ON: YES
Enable when phone is locked: YES
Disable when DND is ON: YES
Enable voice call notification: YES
Enable local notifications: YES
Enable notifications ungroup: YES
Other settings are set to NO.

Thank you!

**Comment by lfom** [comment]
Looks like WeChat use "local" notifications, try enabling standard notifications...

**Comment by ikemanet** [comment]
Nope, I already enabled local notification. You can see my settings above. But I found that if I set Disable standard notifications to NO, I can receive it. But is possible to convert standard notification to custom one? Because I'm using Inverted theme, I'd like to have the same look and feel, the same font size and background color of every notification. Thanks a lot.

**Comment by lfom** [comment]
That's what I said: enabled standard notifications. No, it cannot be converted, notifications system should change soon.
