### ISSUE TITLE
Can install the apk file and the update 1702 in my watch

### ISSUE THREAD

**Issue by stratosv1** [edotassi/AmazMod#294]
I download a watch face .apk format . I have upload to the watchface folder in my amazfit stratos 2 , my amazmod is connected with my phone. I tap the .app file to install . I have a send command and a circle going round and round but no installation happens. The same with the update 1702 not possible to be installed . Moreover  from file explorer I have deleted some watch faces from Watchface Folder ( not the one with the dot in front) and the faces still exist in my phone . What happened guys the app till now was working perfectly

**Comment by lfom** [comment]
You are confusing a lot of things, and made it a mess. Try again, and ask nicely, maybe someone will help you. GitHub isn't meant to support questions, both installing APKs and sending/deleting files are working. Have a nice day.
