### ISSUE TITLE
Reply and close to missing

### ISSUE THREAD

**Issue by mcconkiee** [edotassi/AmazMod#298]
Hi. I love this app. So thank you.

I updated my watch service apkto 1702. App version on phone is 1.0.64ch. I'm not seeing the UI that allowed me to close or reply. My device is running Android 8.1.0. is there a setting I messed up or more info I can provide?

Thanks again!

**Comment by mcconkiee** [comment]
Ohh stratos us version

**Comment by ikemanet** [comment]
Hi, I guess in the new version you need to swipe left to see the reply buttons.

**Comment by diotto** [comment]
The behavior changed in this new version. Swipe left to see the replies and swipe right to dismiss notification.
