### ISSUE TITLE
Custom responses don't appear

### ISSUE THREAD

**Issue by ega6226** [edotassi/AmazMod#299]
Hi,

First of all, thank you so much for making this awesome app.

I have the latest update on both the mobile and the clock (1702). Until today it worked correctly, but today the predefined answers have stopped appearing. I have restarted both devices and nothing.

Thanks for the great job.

Ernesto

**Comment by diotto** [comment]
Hi @ega6226 . The behavior changed in this new version. Swipe left to see the replies and swipe right to dismiss notification.
