### ISSUE TITLE
Please provide the ability to save Amazmode notifications on the watch.

### ISSUE THREAD

**Issue by Veligord** [edotassi/AmazMod#302]
Please provide the ability to save Amazmode notifications on the watch. It is desirable that they be saved in the standard list of notifications.

**Comment by jandrabek** [comment]
I think I just wrote the same issue. Does this mean that custom ui for notifications from Amazmod is visible only for set period of time and after that you cannot access it anymore? Simply when it dissappears you can only see stock notifications right?

**Comment by lfom** [comment]
It's in the roadmap, there is an open issue for this already. Thanks for the input.
