### ISSUE TITLE
Huawei Devices and Recommendations

### ISSUE THREAD

**Issue by andrewk1993** [edotassi/AmazMod#304]
Ok guys. I have issues with my Huawei Devices running EMUI 8.0 . I have tried EVERYTHING relating to power saving mode but there is a problem with RAM management!! My recommendation would be that any missed notifications are pushed to the watch after the device reconnects or even keeping reminding you that you have a notifications. This will fix the issue when the phone keeps disconnecting and reconnects immediately (due to forcing the amazfit app to be killed and being re-opened after a second when you receive a notification).

**Comment by lfom** [comment]
There is an issue open for showing missing notifications on watch when it reconnects to phone.

The only issues as of now that might exist with EMUI are it seems that it may keep the screen status as on when double-tap to wake-up is enabled and sometimes AmazMod does not reconnects to watch if it was disconnected for a long time, but it may be not EMUI-related.
