### ISSUE TITLE
Amazmod connection issue

### ISSUE THREAD

**Issue by halilhassan** [edotassi/AmazMod#305]
I installed the latest version Amazmod (1.0.64ch) and the latest Amazmod Service (1702). All connected and worked fine. Today however the Amazmod app is showing as Disconnected even though the Amazfit app connects without a problem. I have tried rebooting  both the phone and the watch but that does not make any difference. I am using a Huawei Mate 10 Pro with Stratos.
Any help will be appreciated.

**Comment by halilhassan** [comment]
Note: When flicking through the apps on the phone the Service does appear at the end of the list, so the Service is definitely still installed.

**Comment by lfom** [comment]
> Note: When flicking through the apps on the phone the Service does appear at the end of the list, so the Service is definitely still installed.

"Flicking through the apps on the phone"? Service APK must be installed on watch, not on phone. Phone must have stock Amazfit and AmazMod from PlayStore.

**Comment by halilhassan** [comment]
> > Note: When flicking through the apps on the phone the Service does appear at the end of the list, so the Service is definitely still installed.
> 
> "Flicking through the apps on the phone"? Service APK must be installed on watch, not on phone. Phone must have stock Amazfit and AmazMod from PlayStore.

Sorry I meant on the watch.

**Comment by halilhassan** [comment]
Both the app on the phone and the service on the watch are stock. Both were working but is not anymore.

**Comment by edotassi** [comment]
@halilhassan do you have fixed?

**Comment by halilhassan** [comment]
@edotassi unfortunately not. I have removed it as it wasn't worth the hassle.

**Comment by lfom** [comment]
EMUI needs two configurations: stock "disable notifications" and also EMUI's "manual management", so the app can start and keep running in the background. If the watch isn't connected to the phone for a long time, AmazMod may fail to connect again until airplane mode on phone is enabled then disabled.
