### ISSUE TITLE
notifications in the watch are not received

### ISSUE THREAD

**Issue by hnmorgado** [edotassi/AmazMod#306]
My watch suddendly stopped receiving notifications from selected apps.
I think it was after I enable the notificatins ungroup, but not for sure. Because even if I disable it it's not working anymore. I tey to test notifications (in the about menu), and  don't receive any.
But phone is connecte and I can set the brightness and send some commands from tewaking menu. I just don't receive any notification.
My phone is huawei mate 10 pro. I already restarted phone and watch but didn't solve the problem.
Can I send some logs or there's some setting I can try?
- I have installed amazfit service 1702 and amazfit app 1.0.65

Cheers

**Comment by lfom** [comment]
If there is connection and you don't get any test notifications, then you enabled DND on watch. Please be aware that GitHus isn't meant to support questions, check FAQ for the appropriate channels.
