### ISSUE TITLE
Received notifications are gone

### ISSUE THREAD

**Issue by Zipp05** [edotassi/AmazMod#308]
History of notifications dissappear after screen timeout. If you're fast enough, you can read it and sent pre noted replies. After time out screen the replies are gone. And if you swipe up to see notifications, you don't see history of received notifications.

I have "disable standard notification" on right now. Because of that I see the same notifications twice. If I disable that option I only see the custom notification. That is not saved like explained above.
I prefer double notification and save received notification then one notification and have to be quick to read it and reply. 

Can we fix this? 
I have 1702 service, amazfit pace US Rom with Great fit watch face.

**Comment by Zipp05** [comment]
Ahaa I see. Then double notification. Will wait. Do you have a link to the Amazmod road map?
This issue can be closed after that. Sorry for the trouble!

**Comment by edotassi** [comment]
@Zipp05 https://github.com/edotassi/AmazMod/milestones
