### ISSUE TITLE
No pre noted replies

### ISSUE THREAD

**Issue by jessyrmt** [edotassi/AmazMod#309]
After the update in 1702, I do receive SMS notifications but I don't have pre noted replies. Everything works fine once I get back to version 1588.

**Comment by diotto** [comment]
Since 1702 quick replies are available by swiping left in notification. Have you tried? Note that the hide replies turned into hide notification content after this update. So you must have "hide notification content" disabled in phone app and swipe left to see replies. It's described in changelog.

**Comment by jessyrmt** [comment]
Okay, that's fine, I just needed to know that I had to swip left.
Sorry but where can I find this changelog?

**Comment by lfom** [comment]
@jessyrmt 3rd line in 1.0.64 changelog.
