### ISSUE TITLE
FB messenger - only the first notification

### ISSUE THREAD

**Issue by fosiczka** [edotassi/AmazMod#313]
With the last Amazmod I only get the first notification, when I received another message, the first notification will reappear

**Comment by lfom** [comment]
Ungroup is enabled in AmazMod settings? If yes, probably GB changed something in notifications, there isn't much we can do about it...

**Comment by fosiczka** [comment]
Ungroup is enabled in settings

**Comment by lfom** [comment]
Merged with #301.
