### ISSUE TITLE
Time since Full Charge incorrect

### ISSUE THREAD

**Issue by GrinFactor** [edotassi/AmazMod#317]
The time since last full charge on the Service apk says 5 days 12 hours which is incorrect. The Amazfit app says that 48 hours have passed. The Amazefit app is correct.  Service APK version 1702.

**Comment by amoshydra** [comment]
I have been charging my watch for over 30 mins after 100%. However, this is not detected as a full charged. Would it be more meaningful to have the full charge detection be made with some tolerance instead? For example, any battery level above 99% will be considered as full charge?

**Comment by lfom** [comment]
No, it's not. Amazfit shows last time any charger was connect, AmazMod shows last FULL charge.

**Comment by GrinFactor** [comment]
I only charge my watch to 100%, never do a half charge. So there eis definitely something not right. 

Also, what's the point of showing "time since full charge"? Rather do it the same way that the amazfit app does it. It's way more useful to display "time since last charge" as the owner of the watch knows how and why he charged his watch.

But for the record in my example, my watch was fully charged as it was charged overnight.

**Comment by GrinFactor** [comment]
I'm sorry to re-open this one. I've charged my phone watch 100% and used it for the last couple of days. The "Time since full charge" corrected itself after 3 days. Meaning it read the same value as the amazfit app. 

So there is definitely something weird going on. I'm going to test this again and update this thread.
