### ISSUE TITLE
Bug: Notifications not readed properly

### ISSUE THREAD

**Issue by galaterro** [edotassi/AmazMod#318]
Since last update, I can't read notifications via AmazMod. It shows the name of the notification (e.g. the name of the contact in whatsapp) but doesn't show the content of the notification.

I tried uninstalling and installing again, but the problem is still there.

¿Anyone else having the same issue?

**Comment by lfom** [comment]
Disable "Hide notification text" in AmazMod settings (it was "Hide replies) previously.
