### ISSUE TITLE
4.1.5&4.1.6 App doesn't start on Android 4.4.4 on Xpera Z1compact

### ISSUE THREAD

**Issue by Uwe-B** [edotassi/AmazMod#32]
I tried it with booth available version, the App installs fine but just doesn't start on my device. AmazIT 2.4 was installed and removed before, Amazmod_MFTE331_sin_fw.apk does install and work fine.

**Comment by edotassi** [comment]
Can you send a logcat?

**Comment by Uwe-B** [comment]
Sure, I did reinstall it again after deinstalling AmazIT.
And started the app at 19:10
Logcat is attached.
Interesting part seems to be:
05-14 19:10:03.127 E/AndroidRuntime(26406): Caused 
by: java.lang.ClassNotFoundException: Didn't find class 
"com.huami.watch.companion.CompanionApplication" on 
path: DexPathList[[zip file 
"/data/app/com.huami.watch.hmwatchmanager-1.apk"],na
tiveLibraryDirectories=[/data/app-lib/com.huami.watch.hm
watchmanager-1, /vendor/lib, /system/lib]]

Datum:	Mon, 14 May 2018 08:17:10 -0700
Von:	Edoardo Tassinari <notifications@github.com>
Antwort an:	edotassi/AmazMod <reply@reply.github.com>
An:	edotassi/AmazMod <AmazMod@noreply.github.com>
Kopie an:	Uwe-B <nannys.hedgehog@googlemail.com>, 
	Author <author@noreply.github.com>
Betreff:	Re: [edotassi/AmazMod] 4.1.5&4.1.6 App doesn't start on Android 4.4.4
	on Xpera Z1compact (#32)

**Comment by Uwe-B** [comment]
Found a version AmazMod-v4_0_4.apk. Same problem, app crashes at start.

**Comment by edotassi** [comment]
@Uwe-B I think the problem depends on the multidex, I have to check better

**Comment by Uwe-B** [comment]
Eventually this could be helpful:
https://www.jimbobbennett.io/fixing-issues-with-multidex-on-pre-lollipop-devices-on-windows/

**Comment by edotassi** [comment]
With new version i will fix this

**Comment by Uwe-B** [comment]
Thank you very much! I'm looking foreward to it.

**Comment by edotassi** [comment]
see #40
