### ISSUE TITLE
Smartwatch does not connect to Amazmod

### ISSUE THREAD

**Issue by RicoSpm** [edotassi/AmazMod#320]
Hi,

I installed the latest version of the service Amazmod on my Amazfit with AmazIT 8.0 and downloaded the app on my Xiaomi Mi Mix 2s, but tha smartwatch cannot connect to the app. 

How can I solve?

Thank you

**Comment by lfom** [comment]
Check FAQ, you must have stock Amazfit installed and connected to watch. If you have any other app installed on watch that connected to phone via Bluetooth, uninstall. We do not support custom ROM, and GitHub isn't meant for support questions, please refer to FAQ.
