### ISSUE TITLE
After putting account close apk

### ISSUE THREAD

**Issue by Danyldft** [edotassi/AmazMod#4]
I have installed version 2.0 and after adding miui account it jumps a toast di synchronizing and black screen and closing of apk.
My OS is Android 5.1 and Chinese version 2.3 and version 2.3 are working perfectly on my device.
I hope I can solve it.
Here I am for any test you want.
Thank you.

**Comment by edotassi** [comment]
Hi, can you try this version?

[AmazMod_2_1_0-rc1.apk.zip](https://github.com/edotassi/AmazMod/files/1841928/AmazMod_2_1_0-rc1.apk.zip)

**Comment by Danyldft** [comment]
Same problem, after logging in apk does not load.
I try to open later and close

En 23 de marzo de 2018 3:49:19 p. m. Edoardo Tassinari <notifications@github.com> escribió:

Hi, can you try this version?

AmazMod_2_1_0-rc1.apk.zip<https://github.com/edotassi/AmazMod/files/1841928/AmazMod_2_1_0-rc1.apk.zip>

**Comment by Danyldft** [comment]
I sent him video of what he does apk after login.

https://mega.nz/#!yVxGHZ5R!0qbDAJXk0W_juq9D0qDdeUJocPHImVT5k23WENtnebo

**Comment by edotassi** [comment]
try this:

[patched-debug.apk.zip](https://github.com/edotassi/AmazMod/files/1843856/patched-debug.apk.zip)

**Comment by Danyldft** [comment]
Thanks friend!!!!!.
This one is working !!!!
Greetings.

**Comment by edotassi** [comment]
Can you try this?

[patched-debug.apk.zip](https://github.com/edotassi/AmazMod/files/1844166/patched-debug.apk.zip)

I think the problem is the emojis in unicode in the changelog
for now I have removed the emojis

**Comment by Danyldft** [comment]
Perfect, it works ok.
One last bug, when playing in Wechat closes apk too, it is only informative because I do not use that option.
Any test you want is at your disposal.
Greetings and thanks.

**Comment by edotassi** [comment]
Ok, fixed wechat crash with https://github.com/edotassi/AmazMod/commit/d76eb6248eae2c51b286b752b40fd1171b5379e8#diff-766e9d0e78b262eede43d7b84c256299L26
