### ISSUE TITLE
AmazMod future

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#40]
Hello everyone! Sorry for my absence but there were some problems. From version 2.4.0 of the official Huami app is not possible anymore to modify directly the native app, so we decided to take a different way...

We'll make an external app that will use the official app as a bridge for the connection to the watch. On the watch will be installed a small app that will run in background. the advantages are:

- more control

- single link, official app and the new AmazMod will use the same bluetooth connection, so there will be not more battery usage

- by using a single link it's really easy to pair AmazMod to the watch, it's automatic!

I know that installing an external app is annoying, but at the moment is the only way to continue in this project. I promise that the external app will be really light!

**Comment by skubi23t** [comment]
When can we expect the release of this external app?

**Comment by edotassi** [comment]
@skubi23t we are testing internally a first version with some features, I think it will be released in 1/2 weeks

**Comment by skubi23t** [comment]
Is it possible to be a part of a testing team? Maybe I can help you somehow.

**Comment by gidano** [comment]
It would be good to have a pre-release version to have time for translation!<br>Does the app installed on the watch have a language file, should it be translated?

**Comment by edotassi** [comment]
@gidano:
on the watch there aren't translations currently, while on the app I am here: https://github.com/edotassi/AmazMod/blob/master/app/src/main/res/values/strings.xml

@skubi23t do you have telegram?

**Comment by skubi23t** [comment]
Yes, sure. I'm following the official channel. Skubi is my nickname

**Comment by gidano** [comment]
Here is the Hungarian translation.<br/>
[amazmod.new.values.hungarian.translation.txt](https://github.com/edotassi/AmazMod/files/2137230/amazmod.new.values.hungarian.translation.txt)

**Comment by edotassi** [comment]
@gidano can you make a pull request?

**Comment by gidano** [comment]
@edotassi Unfortunately not. I do not know what I should do. I can not find the way... :)
