### ISSUE TITLE
Custom Watchface APK

### ISSUE THREAD

**Issue by GreatApo** [edotassi/AmazMod#41]
In last month I managed to develope a watchface APK that can be customised only through its values XML files.

This means that this watchface could potentially load all its settings externally from a database (among many watchfaces), or be customised by its users.

This could be possible from a project like this. What do you guys think about this idea?

**Comment by edotassi** [comment]
yes, it can be configured directly from the external app

**Comment by edotassi** [comment]
@GreatApo this -> https://github.com/GreatApo/Amazfit-Greatfit-Watchface ?

**Comment by Klaus3d3** [comment]
this sounds like it could be usefull for my xDrip+ widget/ Blood glucose level indication.

**Comment by GreatApo** [comment]
More [here](https://github.com/edotassi/AmazMod/issues/178)
