### ISSUE TITLE
Notifications not always pushing to the watch

### ISSUE THREAD

**Issue by scarapunzi** [edotassi/AmazMod#6]
With latest release installed (on android 8, galaxy s8), the notifications don't always come to the watch. The problem is intermittent and seems not related to any specific situation/app.

**Comment by Danyldft** [comment]
They work very badly for me, I had to remove apk.
Some two doubles and others do not notify anything, such as aquamail emails.
The last version worse than the one that happened to me to prove that it worked removing the emojis.
Let's see if it improves.
A greeting.

**Comment by edotassi** [comment]
we are testing a new version internally with improvements

**Comment by Danyldft** [comment]
Ok, I hope they can be solved.
For now I continue with the GP that works best.

**Comment by edotassi** [comment]
@Danyldft can you try this?
[patched-debug.apk.zip](https://github.com/edotassi/AmazMod/files/1868167/patched-debug.apk.zip)

**Comment by Danyldft** [comment]
I will try when I can and comment.
Thank you

**Comment by Danyldft** [comment]
@edotassi,
What I've tried apk YouTube and Mismarcadores are notifying twice in clock, but I think the fault is for the apk amazfit china, with the GP does not happen and it works fine.
I think everything else in what little I've tried works well.
Greetings.

**Comment by lfom** [comment]
It seems that Notify & Fitness now support Amazfit Pace for notifications only, and it works quite well. Maybe this can help fixing double notifications?

Also, what is GP? Gadgetbridge? Ty

**Comment by Danyldft** [comment]
GP is Google Play and the notifications work perfectly in the Google Play apk.

**Comment by edotassi** [comment]
@Danyldft but with the version from the play store notifications arrive double?

**Comment by Danyldft** [comment]
@edotassi, no, with Google Play version no.
If you can see Google Play code to see what changes

**Comment by lfom** [comment]
I get double notifications for some apps on the Google Play version of Amazfit (EN), for emails (TypeApp, same as BlueMail) and Telegram sometimes...

**Comment by lfom** [comment]
Same here: WhatsApp, TypeApp mail app, Telegram... Most apps that have actions in the notifications are doubled.

**Comment by edotassi** [comment]
@Danyldft and @lfom do you have MIUI?

**Comment by Danyldft** [comment]
No, tengo zopo speed 7.
Rom root stock 5.1.
Saludos

**Comment by edotassi** [comment]
@Danyldft @lfom 
do you confirm that you don't lose notifications?

**Comment by Danyldft** [comment]
No, solo las duplica en muchas ellas.
Solo en la apk mis marcadores que después de duplicarla la borra del teléfono y del reloj, es decir que después de duplicarla además la elimina, pero eso solo me pasa con esa apk.
Le dejo el enlace de la apk.

https://play.google.com/store/apps/details?id=eu.livesport.MisMarcadores_com

**Comment by edotassi** [comment]
tomorrow I will prepare an apk with some more logs
@Danyldft can you try to receive some double notifications and then send me the logcat?

**Comment by Danyldft** [comment]
Si me dice con que apk hacer logcat lo intentaré sin problema a ver si se resuelven.

**Comment by lfom** [comment]
I've run AmazMod on a Samsung S5 mini with stock Android 6.0.1. I can provide logs too, if it helps.

**Comment by Danyldft** [comment]
@edotassi me acabo de fijar que los segundos msj de WhatsApp no me llegan, tengo dos msj en movil y reloj solo muestra 1

**Comment by edotassi** [comment]
fixed with 4.1.6?

**Comment by Estemismo** [comment]
Not fixed for me with 4.1.6

**Comment by lfom** [comment]
There is an app that I cannot make it to work with AmazMod with notifications, it works with CN Amazfit 2.4.0. I don't know if it matters, but it's the same app used for both calls and SMS.
https://play.google.com/store/apps/details?id=com.contapps.android

If I change the SMS app to Yata, then it works normally in AmazMod.

**Comment by edotassi** [comment]
see #40
