### ISSUE TITLE
Can't finish tutorial in Android 8.0 phone

### ISSUE THREAD

**Issue by fcaronte** [edotassi/AmazMod#66]
after I give the notification access it alway say me to grant the notification access and can't close tutorial but the notification are working with default setting of the app (I can see this because I receive notification with phone screen ON)

**Comment by lfom** [comment]
Pull request #67, can somebody test, please?
https://github.com/edotassi/AmazMod/pull/67

**Comment by fcaronte** [comment]
Good Job! I confirm now is working 👍
