### ISSUE TITLE
Not syncing w rom 2.0.27

### ISSUE THREAD

**Issue by Saulinhoo** [edotassi/AmazMod#71]
After the latest update my mod is not syncing steps, sleep and bike rides only shows the battery correct, had to go back to the playstore version and it's working fine

**Comment by lfom** [comment]
AmazMod won't be used to sync data anymore, please see new starting page/ReadMe.

**Comment by lfom** [comment]
As I said previously, I wasn't released yet, if you want to alpha-test it then you must build the apps yourself. ;)
