### ISSUE TITLE
Standup alert not working AmazMod_v3_0_0.apk 

### ISSUE THREAD

**Issue by dawgtx** [edotassi/AmazMod#74]
I just moved from official amazfit app. using the amazfit stratos.
Standup alert was working. 
on amazmod V3.0.0 its not working any more. no alert received.

**Comment by lfom** [comment]
@dawgtx V3.0 is pretty old, please try the most recent one: 4.1.6. Be aware that these versions are now deprecated and they won't be updated.

Actually, this alert isn't related to the app, it's generated on the watch itself, you should check your watch, maybe factory reset/unpair + pair.

**Comment by lfom** [comment]
@dawgtx https://mega.nz/#!FhASyCyK!MZOP-tK79ChPhDPLvcWLYVfSzlMHlESR2s4lhkp4TCY
