### ISSUE TITLE
Notification for connection/disconnection from the phone

### ISSUE THREAD

**Issue by fcaronte** [edotassi/AmazMod#79]
Cold be a good idea to add a notification when phone is connected and disconnected?

**Comment by edotassi** [comment]
is not already implemented in the rom?

**Comment by fcaronte** [comment]
No, unfortunately is a custom rom feature (when I was on Amazfit 8 I have it, but now on stock international I haven't it) I don't know if is present on china stock version

**Comment by lfom** [comment]
Stock ROMs have "find my phone" in settings (Android only, it seems), using PaceOn can warn about connection/disconnection when CXN svc is activated.

**Comment by fcaronte** [comment]
Ok I activated it, usually I use this feature on watchdroid but never see is present on pace on too

**Comment by lfom** [comment]
Latest version as of now should have this option (connection status on main screen), please confirm it's working on release channel so we can close this one. ;)

**Comment by fcaronte** [comment]
Now is working, whe can close
