### ISSUE TITLE
Strava sync - doesn't sync on most occasions

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#8]
Hi, 

I have tested with several sport activities, re-installed the app, revoked the Strava access and tried again.
The sync seems not to be functional. please check :)

Thanks a lot for all the stuff you're doing!

**Comment by Danyldft** [comment]
Ningun problema aquí, siempre me ha sincronizando igual que la apk de play store.
La aplicación solo sube actividades que utilizan gps, si no no las subirá.
Saludos.

**Comment by 1immortal** [comment]
Hi Dany,

Thanks for replying. I've tried running and biking, and in both cases the activity wasn't on Strava.

**Comment by edotassi** [comment]
from what I'm looking at, I think the problem depends on the fact that the account has already been used, with new accounts does not seem to give problems

**Comment by 1immortal** [comment]
Hi Dany,

With my PACE and the same Strava account with the Playstore version, there's no problem with syncing.
I've revoked the token for the PACE, re-paired it again and tried to work with Stratos, but still had the same issue with the watch on a CN rom. with a US rom, there's no issue with syncing with Playstore version and the Stratos flashed to the Intl version.

**Comment by JoseFulgencio** [comment]
Hi, I can not get AmazMod to synchronize with Strava, Strva's account is new, AmazMod says it's synchronized, but it's not uploading any activity. I use it with an AmazFit Stratos with Chinese rom translated into Spanish.
Nor do I find the option to unlink Strava's account in AmazMod.
Thank you..

**Comment by 1immortal** [comment]
@JoseFulgencio  the only way to unlink the Strava sync is from your Strava account under the applications menu, there you will be able to revoke the token and the access of Amazfit to Strava's account

**Comment by skubi23t** [comment]
I have tried to deactivate and activate again. Amazmod says it is synchronized, but there is no activities from my Amazfit in Strava synchronized :( Any idea?

**Comment by edotassi** [comment]
see #40
