### ISSUE TITLE
Custom UI - no body of Google based apps

### ISSUE THREAD

**Issue by 1immortal** [edotassi/AmazMod#86]
Gmail/Hangouts - getting only the header of the message, without the body ( content ).

**Comment by lfom** [comment]
Some notifications use "spannableString" instead of regular String for the content, and it was causing some errors... Working on a fix. ;)

**Comment by lfom** [comment]
@1immortal Should be working as of now, please confirm it's fixed so this can be closed.

**Comment by 1immortal** [comment]
works flawlessly !
