### ISSUE TITLE
Remaining battery estimation

### ISSUE THREAD

**Issue by GreatApo** [edotassi/AmazMod#91]
What would be useful is an estimation of the remaining battery life. This is easy to calculate from the last change time + the battery % and the current battery. Then a dashed liniar line could be displayed in the graph.

Remaining battery time = [ (now_time - last_charge_time)/(last_charge_battery_percent - now_battery_percent) ] * now_battery_percent

The dashed line should start from last charge to 0 at the predicted time

**Comment by GreatApo** [comment]
Graph is ready: #92 
Calculation methods is very simple, last charging point and last measurement.
The remaining time can also be displayed as a number and even be forward to watch (or better calculate it there)

**Comment by lfom** [comment]
I think this can be closed already, right? Thanks @GreatApo! ;)

**Comment by lfom** [comment]
Closed by request of @GreatApo  (I thought you could close issues too :P).
