### ISSUE TITLE
no amazmod settings on stratos 3

### ISSUE THREAD

**Issue by baronkaz** [edotassi/AmazMod#958]
model a1929, rom 4.2.8.0. installed amazmod from pc on phone app it shows that all is working, amazmod connected, but there is no amazmod settings icon on watch. how can i access amazmod settings on watch?

**Comment by GreatApo** [comment]
You need to install the watch/service app on the watch. Keep in mind that amazmod is discontinued and that it doesn't work very well with stratos 3.

**Comment by 1immortal** [comment]
https://youtube.com/shorts/4fAhb6cylqY

בתאריך יום ו׳, 4 במרץ 2022, 11:24, מאת baronkaz ***@***.***>:
