### ISSUE TITLE
Disable backlight during notification

### ISSUE THREAD

**Issue by fr3akyzz** [edotassi/AmazMod#98]
It'll save battery a lot if backlight during notification can be disabled just like the original Amazfit Watch App notification. Just my 2 cents

**Comment by airainchoc** [comment]
If I can give my opinion, it would be nice to leave it as an option if possible

**Comment by fr3akyzz** [comment]
Yes I agree. An option to turn it on/off will be nice

**Comment by lfom** [comment]
Added in commit 7daec042abcae94419b8a0cba4f447a7d817765f, please update both phone and service app, restart both and test so this can be closed.

**Comment by lfom** [comment]
There is a small problem with this feature: so far, there is no way to force watch to go to sleep so the screen may go bright for a few seconds or take a while to go to sleep again after notification closes. And then brightness may be stuck as off if you tap the screen at the wrong moment: fix is easy: access the quick settings drop down menu and change brightness. using 10s for the notification timeout helps as it's more or less the time required for the screen to lock again.
